// ============================================================
// KCHIMBO+ — DEMO DATA (banco de datos local)
// Se usa mientras no hay Google Sheets conectado
// ============================================================

const DEMO_USERS = [
  {
    usuario: "estudiante01",
    password: "abc12345",
    nombre: "Jose Carlos Llano Vilca",
    area: "CIE",
    rol: "estudiante",
    membresia_inicio: "2026-06-01",
    membresia_fin: "2026-08-31",
    intentos: 0,
    bloqueado_hasta: null
  },
  {
    usuario: "admin",
    password: "Admin@2026",
    nombre: "Carlos Llano",
    area: "ADMIN",
    rol: "admin",
    membresia_inicio: "2026-01-01",
    membresia_fin: "2099-12-31",
    intentos: 0,
    bloqueado_hasta: null
  }
];

// ── CLASES (PDFs y Videos) ──────────────────────────────────
const DEMO_CLASES = [
  // ÁLGEBRA
  { id:1, curso:"ÁLGEBRA", semana:1, titulo:"Conjuntos y Operaciones", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>`, color:"#E8521A" },
  { id:2, curso:"ÁLGEBRA", semana:1, titulo:"Conjuntos - Clase en Vivo", tipo:"VIDEO",
    url:"https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>`, color:"#E8521A" },
  { id:3, curso:"ÁLGEBRA", semana:2, titulo:"Expresiones Algebraicas", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`, color:"#E8521A" },
  { id:4, curso:"ÁLGEBRA", semana:2, titulo:"Factorización", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`, color:"#E8521A" },
  { id:21, curso:"ÁLGEBRA", semana:3, titulo:"Radicación y Potenciación", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`, color:"#E8521A" },
  { id:22, curso:"ÁLGEBRA", semana:3, titulo:"Ecuaciones de Primer Grado", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`, color:"#E8521A" },
  { id:23, curso:"ÁLGEBRA", semana:4, titulo:"Ecuaciones Cuadráticas - Video", tipo:"VIDEO",
    url:"https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#E8521A" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>`, color:"#E8521A" },
  // ARITMÉTICA
  { id:5, curso:"ARITMÉTICA", semana:1, titulo:"Números Naturales", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#C0392B" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>`, color:"#C0392B" },
  { id:6, curso:"ARITMÉTICA", semana:1, titulo:"Divisibilidad - Video", tipo:"VIDEO",
    url:"https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#C0392B" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>`, color:"#C0392B" },
  { id:7, curso:"ARITMÉTICA", semana:2, titulo:"MCD y MCM", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🔢", color:"#C0392B" },
  // GEOMETRÍA
  { id:8, curso:"GEOMETRÍA", semana:1, titulo:"Ángulos y Rectas", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"📏", color:"#A04000" },
  { id:9, curso:"GEOMETRÍA", semana:2, titulo:"Triángulos y Propiedades", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"📏", color:"#A04000" },
  { id:10, curso:"GEOMETRÍA", semana:2, titulo:"Geometría - Clase Video", tipo:"VIDEO",
    url:"https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail:"📏", color:"#A04000" },
  // TRIGONOMETRÍA
  { id:11, curso:"TRIGONOMETRÍA", semana:1, titulo:"Razones Trigonométricas", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"📊", color:"#884EA0" },
  { id:12, curso:"TRIGONOMETRÍA", semana:2, titulo:"Identidades Trigonométricas", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"📊", color:"#884EA0" },
  // FÍSICA
  { id:13, curso:"FÍSICA", semana:1, titulo:"Cinemática", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"⚡", color:"#2980B9" },
  { id:14, curso:"FÍSICA", semana:1, titulo:"Dinámica - Video", tipo:"VIDEO",
    url:"https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnail:"⚡", color:"#2980B9" },
  // QUÍMICA
  { id:15, curso:"QUÍMICA", semana:1, titulo:"Tabla Periódica", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🧪", color:"#27AE60" },
  { id:16, curso:"QUÍMICA", semana:2, titulo:"Estequiometría", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🧪", color:"#27AE60" },
  // BIOLOGÍA
  { id:17, curso:"BIOLOGÍA", semana:1, titulo:"La Célula", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🔬", color:"#F39C12" },
  { id:18, curso:"BIOLOGÍA", semana:2, titulo:"Genética Mendeliana", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🔬", color:"#F39C12" },
  // LENGUAJE
  { id:19, curso:"LENGUAJE", semana:1, titulo:"Comprensión Lectora", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"📚", color:"#E74C3C" },
  // HISTORIA
  { id:20, curso:"HISTORIA", semana:1, titulo:"Perú Pre-Inca", tipo:"PDF",
    url:"https://drive.google.com/file/d/19MI4rz0BhrVoPGuFXPFXO4ujFQkLQZM-/view?usp=sharing",
    thumbnail:"🏛️", color:"#8E44AD" },
];

// ── RESÚMENES ──────────────────────────────────────────────
const DEMO_RESUMENES = [
  { id:1, curso:"ÁLGEBRA", tema:"Conjuntos", titulo:"Resumen: Conjuntos y Operaciones", url:"#", paginas:4 },
  { id:2, curso:"ÁLGEBRA", tema:"Factorización", titulo:"Resumen: Técnicas de Factorización", url:"#", paginas:6 },
  { id:3, curso:"ARITMÉTICA", tema:"Divisibilidad", titulo:"Resumen: Criterios de Divisibilidad", url:"#", paginas:3 },
  { id:4, curso:"ARITMÉTICA", tema:"Fracciones", titulo:"Resumen: Operaciones con Fracciones", url:"#", paginas:5 },
  { id:5, curso:"GEOMETRÍA", tema:"Triángulos", titulo:"Resumen: Propiedades de Triángulos", url:"#", paginas:7 },
  { id:6, curso:"TRIGONOMETRÍA", tema:"Identidades", titulo:"Resumen: Identidades Trigonométricas", url:"#", paginas:4 },
  { id:7, curso:"FÍSICA", tema:"Cinemática", titulo:"Resumen: Movimiento Rectilíneo", url:"#", paginas:8 },
  { id:8, curso:"QUÍMICA", tema:"Estequiometría", titulo:"Resumen: Cálculos Estequiométricos", url:"#", paginas:6 },
  { id:9, curso:"BIOLOGÍA", tema:"Célula", titulo:"Resumen: Estructura Celular", url:"#", paginas:5 },
  { id:10, curso:"LENGUAJE", tema:"Ortografía", titulo:"Resumen: Reglas Ortográficas", url:"#", paginas:4 },
  { id:11, curso:"HISTORIA", tema:"Imperio Inca", titulo:"Resumen: Organización del Tahuantinsuyo", url:"#", paginas:6 },
  { id:12, curso:"GEOGRAFÍA", tema:"Relieve", titulo:"Resumen: Regiones Naturales del Perú", url:"#", paginas:5 },
];

// ── BANCO DE PREGUNTAS DEMO ────────────────────────────────
// Distribución examen UNA PUNO (área CIE): 60 preguntas
// Álgebra:8, Aritmética:6, Geometría:6, Trigonometría:5,
// Física:8, Química:8, Biología:8, Lenguaje:5, Historia:3, Geografía:3
const DEMO_PREGUNTAS = [
  // ── ÁLGEBRA (8 preguntas en examen) ──
  {id:1, curso:"ÁLGEBRA", area:"CIE", tema:"Conjuntos",
   pregunta:"Si A = {1, 2, 3, 4, 5} y B = {3, 4, 5, 6, 7}, ¿cuántos elementos tiene A ∪ B?",
   a:"5", b:"7", c:"3", d:"8", e:"6", respuesta:"B", año:2023},
  {id:2, curso:"ÁLGEBRA", area:"CIE", tema:"Conjuntos",
   pregunta:"Si n(A) = 20, n(B) = 15 y n(A ∩ B) = 8, entonces n(A ∪ B) es:",
   a:"43", b:"27", c:"35", d:"20", e:"15", respuesta:"B", año:2022},
  {id:3, curso:"ÁLGEBRA", area:"CIE", tema:"Factorización",
   pregunta:"Factorizar completamente: x² - 9",
   a:"(x+3)(x-3)", b:"(x-3)²", c:"(x+9)(x-1)", d:"(x+3)²", e:"x(x-9)", respuesta:"A", año:2023},
  {id:4, curso:"ÁLGEBRA", area:"CIE", tema:"Ecuaciones",
   pregunta:"Si 3x + 7 = 22, entonces x es igual a:",
   a:"3", b:"7", c:"5", d:"4", e:"6", respuesta:"C", año:2022},
  {id:5, curso:"ÁLGEBRA", area:"CIE", tema:"Sistemas",
   pregunta:"El valor de x en el sistema: 2x + y = 10, x - y = 2 es:",
   a:"3", b:"5", c:"4", d:"6", e:"2", respuesta:"C", año:2021},
  {id:6, curso:"ÁLGEBRA", area:"CIE", tema:"Polinomios",
   pregunta:"El grado del polinomio P(x) = 4x⁵ - 3x³ + 2x - 7 es:",
   a:"3", b:"4", c:"5", d:"7", e:"2", respuesta:"C", año:2023},
  {id:7, curso:"ÁLGEBRA", area:"CIE", tema:"Progresiones",
   pregunta:"En una progresión aritmética cuyo primer término es 3 y razón 4, el décimo término es:",
   a:"39", b:"43", c:"35", d:"40", e:"37", respuesta:"A", año:2022},
  {id:8, curso:"ÁLGEBRA", area:"CIE", tema:"Inecuaciones",
   pregunta:"La solución de 2x - 5 > 7 es:",
   a:"x > 1", b:"x > 6", c:"x < 6", d:"x > 5", e:"x > 3", respuesta:"B", año:2021},
  // ── ARITMÉTICA (6 preguntas) ──
  {id:9, curso:"ARITMÉTICA", area:"CIE", tema:"Divisibilidad",
   pregunta:"El MCD de 24 y 36 es:",
   a:"6", b:"8", c:"12", d:"4", e:"18", respuesta:"C", año:2023},
  {id:10, curso:"ARITMÉTICA", area:"CIE", tema:"Fracciones",
   pregunta:"Simplificar: 3/4 + 1/3 =",
   a:"4/7", b:"13/12", c:"4/12", d:"7/12", e:"11/12", respuesta:"B", año:2022},
  {id:11, curso:"ARITMÉTICA", area:"CIE", tema:"Porcentajes",
   pregunta:"¿Cuánto es el 15% de 240?",
   a:"24", b:"36", c:"30", d:"40", e:"48", respuesta:"B", año:2023},
  {id:12, curso:"ARITMÉTICA", area:"CIE", tema:"Potenciación",
   pregunta:"Calcular: 2³ × 2⁴ =",
   a:"2¹²", b:"4⁷", c:"2⁷", d:"2¹", e:"4¹²", respuesta:"C", año:2022},
  {id:13, curso:"ARITMÉTICA", area:"CIE", tema:"Radicales",
   pregunta:"Simplificar: √(144) =",
   a:"11", b:"12", c:"13", d:"14", e:"10", respuesta:"B", año:2021},
  {id:14, curso:"ARITMÉTICA", area:"CIE", tema:"Sucesiones",
   pregunta:"En la sucesión 2, 4, 8, 16, ..., el término siguiente es:",
   a:"18", b:"20", c:"32", d:"24", e:"28", respuesta:"C", año:2023},
  // ── GEOMETRÍA (6 preguntas) ──
  {id:15, curso:"GEOMETRÍA", area:"CIE", tema:"Ángulos",
   pregunta:"Si dos ángulos son suplementarios y uno mide 70°, ¿cuánto mide el otro?",
   a:"90°", b:"110°", c:"120°", d:"70°", e:"20°", respuesta:"B", año:2023},
  {id:16, curso:"GEOMETRÍA", area:"CIE", tema:"Triángulos",
   pregunta:"En un triángulo rectángulo, si los catetos miden 3 y 4, la hipotenusa mide:",
   a:"6", b:"7", c:"5", d:"4", e:"8", respuesta:"C", año:2022},
  {id:17, curso:"GEOMETRÍA", area:"CIE", tema:"Circunferencia",
   pregunta:"El área de un círculo de radio 5 cm es: (π ≈ 3.14)",
   a:"78.5 cm²", b:"31.4 cm²", c:"15.7 cm²", d:"62.8 cm²", e:"50 cm²", respuesta:"A", año:2023},
  {id:18, curso:"GEOMETRÍA", area:"CIE", tema:"Perímetros",
   pregunta:"El perímetro de un cuadrado de lado 7 cm es:",
   a:"21 cm", b:"49 cm", c:"14 cm", d:"28 cm", e:"35 cm", respuesta:"D", año:2022},
  {id:19, curso:"GEOMETRÍA", area:"CIE", tema:"Áreas",
   pregunta:"El área de un trapecio con bases 8 y 12, y altura 5 es:",
   a:"50", b:"40", c:"60", d:"45", e:"55", respuesta:"A", año:2021},
  {id:20, curso:"GEOMETRÍA", area:"CIE", tema:"Polígonos",
   pregunta:"¿Cuántos lados tiene un hexágono?",
   a:"5", b:"8", c:"7", d:"6", e:"9", respuesta:"D", año:2023},
  // ── TRIGONOMETRÍA (5 preguntas) ──
  {id:21, curso:"TRIGONOMETRÍA", area:"CIE", tema:"Razones",
   pregunta:"En un triángulo rectángulo, si el ángulo A = 30°, entonces sen(30°) es:",
   a:"√3/2", b:"1/√2", c:"1/2", d:"√3", e:"2", respuesta:"C", año:2023},
  {id:22, curso:"TRIGONOMETRÍA", area:"CIE", tema:"Razones",
   pregunta:"El valor de cos(60°) es:",
   a:"1", b:"0", c:"√3/2", d:"1/2", e:"√3", respuesta:"D", año:2022},
  {id:23, curso:"TRIGONOMETRÍA", area:"CIE", tema:"Identidades",
   pregunta:"La identidad fundamental es: sen²(x) + cos²(x) =",
   a:"0", b:"2", c:"1", d:"sen(2x)", e:"tg(x)", respuesta:"C", año:2023},
  {id:24, curso:"TRIGONOMETRÍA", area:"CIE", tema:"Ángulos",
   pregunta:"Convertir 180° a radianes:",
   a:"π/2", b:"2π", c:"π", d:"3π/2", e:"π/4", respuesta:"C", año:2022},
  {id:25, curso:"TRIGONOMETRÍA", area:"CIE", tema:"Ecuaciones",
   pregunta:"Si tg(x) = 1 y 0° < x < 90°, entonces x es:",
   a:"30°", b:"60°", c:"90°", d:"45°", e:"15°", respuesta:"D", año:2021},
  // ── FÍSICA (8 preguntas) ──
  {id:26, curso:"FÍSICA", area:"CIE", tema:"Cinemática",
   pregunta:"Un objeto en caída libre desde el reposo, ¿qué velocidad alcanza en 3 segundos? (g = 10 m/s²)",
   a:"10 m/s", b:"20 m/s", c:"30 m/s", d:"40 m/s", e:"50 m/s", respuesta:"C", año:2023},
  {id:27, curso:"FÍSICA", area:"CIE", tema:"Dinámica",
   pregunta:"La fuerza necesaria para acelerar una masa de 5 kg a 4 m/s² es:",
   a:"1.25 N", b:"9 N", c:"20 N", d:"25 N", e:"40 N", respuesta:"C", año:2022},
  {id:28, curso:"FÍSICA", area:"CIE", tema:"Trabajo y Energía",
   pregunta:"Si se aplica una fuerza de 10 N sobre un cuerpo que se desplaza 5 m, el trabajo realizado es:",
   a:"2 J", b:"15 J", c:"50 J", d:"100 J", e:"500 J", respuesta:"C", año:2023},
  {id:29, curso:"FÍSICA", area:"CIE", tema:"Óptica",
   pregunta:"La velocidad de la luz en el vacío es aproximadamente:",
   a:"3×10⁶ m/s", b:"3×10⁸ m/s", c:"3×10¹⁰ m/s", d:"3×10⁴ m/s", e:"3×10¹² m/s", respuesta:"B", año:2022},
  {id:30, curso:"FÍSICA", area:"CIE", tema:"Calor",
   pregunta:"La unidad del calor en el SI es:",
   a:"Caloría", b:"BTU", c:"Joule", d:"Watt", e:"Newton", respuesta:"C", año:2021},
  {id:31, curso:"FÍSICA", area:"CIE", tema:"Electricidad",
   pregunta:"La ley de Ohm establece que V = I × R. Si I = 2 A y R = 10 Ω, entonces V es:",
   a:"5 V", b:"12 V", c:"8 V", d:"20 V", e:"0.2 V", respuesta:"D", año:2023},
  {id:32, curso:"FÍSICA", area:"CIE", tema:"Ondas",
   pregunta:"La frecuencia de una onda que tiene periodo de 0.5 s es:",
   a:"0.5 Hz", b:"1 Hz", c:"2 Hz", d:"4 Hz", e:"0.25 Hz", respuesta:"C", año:2022},
  {id:33, curso:"FÍSICA", area:"CIE", tema:"Cinemática",
   pregunta:"Un móvil recorre 120 m en 8 s con movimiento uniforme. Su velocidad es:",
   a:"10 m/s", b:"12 m/s", c:"15 m/s", d:"16 m/s", e:"20 m/s", respuesta:"C", año:2021},
  // ── QUÍMICA (8 preguntas) ──
  {id:34, curso:"QUÍMICA", area:"CIE", tema:"Tabla Periódica",
   pregunta:"El número atómico del carbono (C) es:",
   a:"4", b:"6", c:"8", d:"12", e:"14", respuesta:"B", año:2023},
  {id:35, curso:"QUÍMICA", area:"CIE", tema:"Enlace Químico",
   pregunta:"El enlace que se forma entre un metal y un no metal es:",
   a:"Covalente", b:"Metálico", c:"Hidrógeno", d:"Iónico", e:"Van der Waals", respuesta:"D", año:2022},
  {id:36, curso:"QUÍMICA", area:"CIE", tema:"Estequiometría",
   pregunta:"La masa molecular del agua (H₂O) es: (H=1, O=16)",
   a:"16", b:"17", c:"18", d:"19", e:"20", respuesta:"C", año:2023},
  {id:37, curso:"QUÍMICA", area:"CIE", tema:"Soluciones",
   pregunta:"La concentración molar de una solución es:",
   a:"g/mL", b:"mol/L", c:"g/mol", d:"mL/mol", e:"L/g", respuesta:"B", año:2022},
  {id:38, curso:"QUÍMICA", area:"CIE", tema:"Reacciones",
   pregunta:"En la reacción: 2H₂ + O₂ → 2H₂O, ¿cuántas moles de agua se producen por mol de O₂?",
   a:"1", b:"3", c:"4", d:"2", e:"0.5", respuesta:"D", año:2021},
  {id:39, curso:"QUÍMICA", area:"CIE", tema:"pH",
   pregunta:"Una solución ácida tiene pH:",
   a:"Mayor a 7", b:"Igual a 7", c:"Menor a 7", d:"Igual a 14", e:"Entre 8 y 14", respuesta:"C", año:2023},
  {id:40, curso:"QUÍMICA", area:"CIE", tema:"Gases",
   pregunta:"La ley de Boyle establece que a temperatura constante, P × V es:",
   a:"Variable", b:"Cero", c:"Constante", d:"Igual a nRT", e:"Igual a P/V", respuesta:"C", año:2022},
  {id:41, curso:"QUÍMICA", area:"CIE", tema:"Química Orgánica",
   pregunta:"El metano (CH₄) es el miembro más simple de la familia de:",
   a:"Alquenos", b:"Alquinos", c:"Alcanos", d:"Alcoholes", e:"Ácidos", respuesta:"C", año:2021},
  // ── BIOLOGÍA (8 preguntas) ──
  {id:42, curso:"BIOLOGÍA", area:"CIE", tema:"Célula",
   pregunta:"La unidad funcional y estructural de los seres vivos es:",
   a:"Tejido", b:"Célula", c:"Órgano", d:"Molécula", e:"Sistema", respuesta:"B", año:2023},
  {id:43, curso:"BIOLOGÍA", area:"CIE", tema:"Genética",
   pregunta:"El ADN se localiza principalmente en:",
   a:"Ribosoma", b:"Mitocondria", c:"Núcleo", d:"Membrana", e:"Citoplasma", respuesta:"C", año:2022},
  {id:44, curso:"BIOLOGÍA", area:"CIE", tema:"Fotosíntesis",
   pregunta:"La fotosíntesis ocurre en el:",
   a:"Núcleo", b:"Mitocondria", c:"Ribosoma", d:"Cloroplasto", e:"Vacuola", respuesta:"D", año:2023},
  {id:45, curso:"BIOLOGÍA", area:"CIE", tema:"Herencia",
   pregunta:"Si un gen es dominante (A) y otro recesivo (a), el fenotipo de Aa es:",
   a:"Recesivo", b:"Codominante", c:"Intermedio", d:"Dominante", e:"Nulo", respuesta:"D", año:2022},
  {id:46, curso:"BIOLOGÍA", area:"CIE", tema:"Respiración",
   pregunta:"El principal producto de la respiración celular es:",
   a:"Glucosa", b:"Agua", c:"ATP", d:"O₂", e:"CO₂ solamente", respuesta:"C", año:2021},
  {id:47, curso:"BIOLOGÍA", area:"CIE", tema:"Taxonomía",
   pregunta:"El reino que incluye a los hongos es:",
   a:"Monera", b:"Protista", c:"Plantae", d:"Animalia", e:"Fungi", respuesta:"E", año:2023},
  {id:48, curso:"BIOLOGÍA", area:"CIE", tema:"Ecología",
   pregunta:"La cadena alimenticia comienza con:",
   a:"Carnívoros", b:"Descomponedores", c:"Productores", d:"Herbívoros", e:"Omnívoros", respuesta:"C", año:2022},
  {id:49, curso:"BIOLOGÍA", area:"CIE", tema:"Evolución",
   pregunta:"La teoría de la selección natural fue propuesta por:",
   a:"Mendel", b:"Pasteur", c:"Lamarck", d:"Darwin", e:"Watson", respuesta:"D", año:2021},
  // ── LENGUAJE (5 preguntas) ──
  {id:50, curso:"LENGUAJE", area:"CIE", tema:"Gramática",
   pregunta:"¿Cuál de las siguientes palabras es un sustantivo?",
   a:"correr", b:"rápido", c:"belleza", d:"hacia", e:"porque", respuesta:"C", año:2023},
  {id:51, curso:"LENGUAJE", area:"CIE", tema:"Ortografía",
   pregunta:"¿Cuál es la tilde correcta en: 'el/él fue'?",
   a:"No lleva tilde", b:"Ambas llevan tilde", c:"'él' lleva tilde para diferenciarlo del artículo", d:"Solo el artículo lleva tilde", e:"Ninguna tiene tilde", respuesta:"C", año:2022},
  {id:52, curso:"LENGUAJE", area:"CIE", tema:"Literatura",
   pregunta:"'El Quijote' fue escrito por:",
   a:"Lope de Vega", b:"Góngora", c:"Quevedo", d:"Cervantes", e:"Calderón", respuesta:"D", año:2023},
  {id:53, curso:"LENGUAJE", area:"CIE", tema:"Comprensión",
   pregunta:"Un sinónimo de 'veraz' es:",
   a:"Falso", b:"Honesto", c:"Lento", d:"Confuso", e:"Breve", respuesta:"B", año:2022},
  {id:54, curso:"LENGUAJE", area:"CIE", tema:"Comunicación",
   pregunta:"¿Qué función del lenguaje predomina en un poema que expresa emociones del poeta?",
   a:"Referencial", b:"Apelativa", c:"Fática", d:"Poética", e:"Expresiva", respuesta:"E", año:2021},
  // ── HISTORIA (3 preguntas) ──
  {id:55, curso:"HISTORIA", area:"CIE", tema:"Perú Prehispánico",
   pregunta:"El Imperio Inca tenía su capital en:",
   a:"Lima", b:"Cusco", c:"Machu Picchu", d:"Cajamarca", e:"Tiahuanaco", respuesta:"B", año:2023},
  {id:56, curso:"HISTORIA", area:"CIE", tema:"Conquista",
   pregunta:"Francisco Pizarro capturó al Inca Atahualpa en:",
   a:"Cusco", b:"Lima", c:"Cajamarca", d:"Quito", e:"Huancavelica", respuesta:"C", año:2022},
  {id:57, curso:"HISTORIA", area:"CIE", tema:"República",
   pregunta:"El Libertador que proclamó la independencia del Perú fue:",
   a:"Bolívar", b:"San Martín", c:"Sucre", d:"O'Higgins", e:"Miranda", respuesta:"B", año:2021},
  // ── GEOGRAFÍA (3 preguntas) ──
  {id:58, curso:"GEOGRAFÍA", area:"CIE", tema:"Perú",
   pregunta:"El río más largo del Perú es:",
   a:"Mantaro", b:"Ucayali", c:"Urubamba", d:"Amazonas", e:"Marañón", respuesta:"D", año:2023},
  {id:59, curso:"GEOGRAFÍA", area:"CIE", tema:"Regiones",
   pregunta:"La región de Puno se caracteriza por:",
   a:"Selva tropical", b:"Desierto costero", c:"Altiplano andino", d:"Bosques húmedos", e:"Valles interandinos", respuesta:"C", año:2022},
  {id:60, curso:"GEOGRAFÍA", area:"CIE", tema:"Hidrografía",
   pregunta:"El lago navegable más alto del mundo se ubica entre Perú y Bolivia, y se llama:",
   a:"Titicaca", b:"Junín", c:"Poopo", d:"Huascarán", e:"Lago Sauce", respuesta:"A", año:2021},

  // ── LETRAS área ── (algunas adicionales para el área LETRAS)
  {id:61, curso:"LENGUAJE", area:"LETRAS", tema:"Gramática",
   pregunta:"¿Cuántas sílabas tiene la palabra 'mariposa'?",
   a:"3", b:"4", c:"5", d:"6", e:"2", respuesta:"B", año:2023},
  {id:62, curso:"HISTORIA", area:"LETRAS", tema:"Historia Universal",
   pregunta:"La Primera Guerra Mundial comenzó en:",
   a:"1910", b:"1912", c:"1914", d:"1918", e:"1920", respuesta:"C", año:2022},
  {id:63, curso:"FILOSOFÍA", area:"LETRAS", tema:"Filosofía Antigua",
   pregunta:"Sócrates fue maestro de:",
   a:"Aristóteles", b:"Platón", c:"Tales de Mileto", d:"Heráclito", e:"Epicuro", respuesta:"B", año:2023},
  {id:64, curso:"FILOSOFÍA", area:"LETRAS", tema:"Lógica",
   pregunta:"Si 'todos los A son B' y 'Juan es A', entonces:",
   a:"Juan puede ser B", b:"Juan no es B", c:"Juan es B", d:"No se puede concluir", e:"Juan es A y no B", respuesta:"C", año:2022},
  {id:65, curso:"ECONOMÍA", area:"LETRAS", tema:"Conceptos Básicos",
   pregunta:"La macroeconomía estudia:",
   a:"Empresas individuales", b:"Comportamiento del consumidor", c:"La economía global y nacional", d:"Precios de productos específicos", e:"Decisiones familiares", respuesta:"C", año:2021},
];

// ── DISTRIBUCIÓN EXAMEN UNA PUNO ──────────────────────────
const DISTRIBUCION_EXAMEN = {
  CIE: {
    "ÁLGEBRA": 8,
    "ARITMÉTICA": 6,
    "GEOMETRÍA": 6,
    "TRIGONOMETRÍA": 5,
    "FÍSICA": 8,
    "QUÍMICA": 8,
    "BIOLOGÍA": 8,
    "LENGUAJE": 5,
    "HISTORIA": 3,
    "GEOGRAFÍA": 3
  },
  LETRAS: {
    "LENGUAJE": 12,
    "LITERATURA": 8,
    "HISTORIA": 8,
    "GEOGRAFÍA": 8,
    "FILOSOFÍA": 8,
    "ECONOMÍA": 6,
    "ÁLGEBRA": 4,
    "ARITMÉTICA": 3,
    "GEOMETRÍA": 3
  }
};

// ── HISTORIAL SIMULACROS (demo) ───────────────────────────
const DEMO_HISTORIAL = [
  { fecha:"2026-07-10", correctas:38, incorrectas:15, blanco:7, puntaje:34.25, area:"CIE" },
  { fecha:"2026-07-05", correctas:32, incorrectas:20, blanco:8, puntaje:27.0, area:"CIE" },
  { fecha:"2026-06-28", correctas:42, incorrectas:12, blanco:6, puntaje:39.0, area:"CIE" },
];

// Cursos disponibles por área
const CURSOS_POR_AREA = {
  CIE: ["ÁLGEBRA","ARITMÉTICA","GEOMETRÍA","TRIGONOMETRÍA","FÍSICA","QUÍMICA","BIOLOGÍA","LENGUAJE","HISTORIA","GEOGRAFÍA"],
  LETRAS: ["LENGUAJE","LITERATURA","HISTORIA","GEOGRAFÍA","FILOSOFÍA","ECONOMÍA","ÁLGEBRA","ARITMÉTICA","GEOMETRÍA"],
  ADMIN: ["ÁLGEBRA","ARITMÉTICA","GEOMETRÍA","TRIGONOMETRÍA","FÍSICA","QUÍMICA","BIOLOGÍA","LENGUAJE","HISTORIA","GEOGRAFÍA","FILOSOFÍA","ECONOMÍA"]
};

// Obtener temas por curso
function getTemasForCurso(curso) {
  const preguntas = DEMO_PREGUNTAS.filter(p => p.curso === curso);
  return [...new Set(preguntas.map(p => p.tema))];
}
